# Generated by Django 5.0.1 on 2024-02-22 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penyewaan',
            fields=[
                ('PenyewaanID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('TanggalSewa', models.DateField()),
                ('Status', models.CharField(choices=[('Proses', 'Proses'), ('Konfirmasi', 'Konfirmasi')], max_length=10)),
                ('MobilID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.mobil')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
