# Generated by Django 5.0.1 on 2024-02-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('MobilID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Merek', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Tahun', models.IntegerField()),
                ('Status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Sedang Disewa', 'Sedang Disewa')], max_length=15)),
            ],
        ),
    ]
